spring.application.name=api_gateway
server.port=8080

# ================= AUTH SERVICE =================
#....using gateway.....FOR POST().............http://localhost:8080/auth/register
#FOR GET()......http://localhost:8080/auth/user?email=sakshi1@example.com
spring.cloud.gateway.routes[0].id=auth_service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# ================= PRODUCT SERVICE =================
#FOR POST()->....http://localhost:8080/product/addProduct
#FOR GET()-->....http://localhost:8080/product/products
spring.cloud.gateway.routes[1].id=product_service
spring.cloud.gateway.routes[1].uri=http://localhost:8282
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**

# ================= CART SERVICE =================
#FOR POST()-->....http://localhost:8080/cart/addToCart
#FOR GET()->....http://localhost:8080/cart/carts?userId=5
spring.cloud.gateway.routes[2].id=cart_service
spring.cloud.gateway.routes[2].uri=http://localhost:7070
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart/**

# ================= ORDER SERVICE =================
#FOR POST()-->....http://localhost:8080/order/placeOrder
#FOR GET()-->.....http://localhost:8080/order/orders?userId=2
spring.cloud.gateway.routes[3].id=order_service
spring.cloud.gateway.routes[3].uri=http://localhost:8181
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/**

